CREATE TABLE IF NOT EXISTS posts (
	id 			SERIAL PRIMARY KEY,
	title 		VARCHAR(255) NOT NULL,
	content 	TEXT NOT NULL,
	category	VARCHAR(255),
	created_at	TIMESTAMPTZ,
	updated_at	TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS tags (
	id			SERIAL PRIMARY KEY,
	tag			VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS posts_tags (
	id			SERIAL PRIMARY KEY,
	id_post		INTEGER REFERENCES posts(id) ON DELETE CASCADE,
	id_tag		INTEGER REFERENCES tags(id) ON DELETE CASCADE
);